package com.imagewatch.ultra2

/** Nombres de grupos y claves, extraídos de los enums protobuf del APK de HiwatchPro (Profile$PBSmartBandCommandId*). */
object Names {
    val groups: Map<Int, String> = mapOf(
        0x11 to "FirmwareUpgrade",
        0x12 to "Setting",
        0x13 to "Binding",
        0x14 to "StrappedEquipment",
        0x15 to "Sport",
        0x16 to "ResetDevice",
        0x17 to "MsgPushSwitch",
        0x18 to "AlarmLists",
        0x19 to "OtherSetInfo",
        0x1A to "SetInfoByKey",
        0x1B to "TestMode",
        0x1C to "DeviceControlApp",
        0x1D to "DeviceReset",
        0x1F to "DialUpdate",
        0x20 to "DialUpdateRead",
        0x21 to "VoiceSh",
        0x22 to "File",
        0x23 to "FileResponse",
        0x24 to "FileVoiceChat"
    )
    val keys: Map<Int, Map<Int, String>> = mapOf(
        0x12 to mapOf(
            0x01 to "SettingKeySycTime",
            0x02 to "SettingKeyAlarmClock",
            0x03 to "SettingKeySetStepTarget",
            0x04 to "SettingKeySetUserInfo",
            0x05 to "SettingKeySetLongSitRemind",
            0x06 to "SettingKeySetHandSide",
            0x07 to "SettingKeySetCallRemind",
            0x08 to "SettingKeyTaishou",
            0x09 to "SettingKeyBrightScreen",
            0x0A to "SettingKeyIsPair",
            0x0B to "SettingKeyFindMe",
            0x0C to "SettingKeyTakePhoto",
            0x0D to "SettingKeyHeartRateSwitch",
            0x0E to "SettingKeyBloodPressureSwitch",
            0x0F to "SettingKeySleepSwitch",
            0x10 to "SettingKeyTestDataSwitch",
            0x11 to "SettingKeyPhoneCallPush",
            0x12 to "SettingKeyNotifyMsgPush",
            0x13 to "SettingKeySycContracts",
            0x14 to "SettingKeyDisturbSwitch",
            0x15 to "SettingKeyLanguage",
            0x16 to "SettingKeyHeartAuto",
            0x17 to "SettingKeyDelteContract",
            0x18 to "SettingKeyMeasure",
            0x19 to "SettingKeyEnterOtaMode",
            0x1A to "SettingMeasureECG",
            0x20 to "SettingKeyWeather",
            0x21 to "SettingKeyTempUnite",
            0x22 to "SettingKeySetTartSportTime",
            0x23 to "SettingKeySetTartStandTime",
            0x24 to "SettingKeyMeasure2",
            0x25 to "SettingKeyContractSOS",
            0x26 to "SettingKeyPay",
            0x27 to "SettingKeyAliPayTouChuan",
            0x28 to "SettingKeyWeather2",
            0xF9 to "SettingSleepBegin",
            0xFD to "SettingShutdown",
            0xFE to "SettingHeartRate",
            0xFF to "PhoneType"
        ),
        0x1A to mapOf(
            0x01 to "SettingKeySycTime",
            0x02 to "SettingKeyAlarmClock",
            0x03 to "SettingKeySetStepTarget",
            0x04 to "SettingKeySetUserInfo",
            0x05 to "SettingKeySetLongSitRemind",
            0x06 to "SettingKeySetHandSide",
            0x07 to "SettingKeySetCallRemind",
            0x08 to "SettingKeyTaishou",
            0x09 to "SettingKeyBrightScreen",
            0x0A to "SettingKeyIsPair",
            0x0B to "SettingKeyFindMe",
            0x0C to "SettingKeyTakePhoto",
            0x0D to "SettingKeyHeartRateSwitch",
            0x0E to "SettingKeyBloodPressureSwitch",
            0x0F to "SettingKeySleepSwitch",
            0x10 to "SettingKeyTestDataSwitch",
            0x11 to "SettingKeyPhoneCallPush",
            0x12 to "SettingKeyNotifyMsgPush",
            0x13 to "SettingKeySycContracts",
            0x14 to "SettingKeyDisturbSwitch",
            0x15 to "SettingKeyLanguage",
            0x16 to "SettingKeyHeartAuto",
            0x17 to "SettingKeyDelteContract",
            0x18 to "SettingKeyMeasure",
            0x19 to "SettingKeyEnterOtaMode",
            0x1A to "SettingMeasureECG",
            0x20 to "SettingKeyWeather",
            0x21 to "SettingKeyTempUnite",
            0x22 to "SettingKeySetTartSportTime",
            0x23 to "SettingKeySetTartStandTime",
            0x24 to "SettingKeyMeasure2",
            0x25 to "SettingKeyContractSOS",
            0x26 to "SettingKeyPay",
            0x27 to "SettingKeyAliPayTouChuan",
            0x28 to "SettingKeyWeather2",
            0xF9 to "SettingSleepBegin",
            0xFD to "SettingShutdown",
            0xFE to "SettingHeartRate",
            0xFF to "PhoneType"
        ),
        0x15 to mapOf(
            0x01 to "SportKeyGet",
            0x02 to "SportKeySportDataRecive",
            0x03 to "SportKeySleepDataRecive",
            0x04 to "SportKeyHeartRateRecive",
            0x05 to "SportKeyBloodDataRecive",
            0x06 to "SportKeyDataTransferOnTimeSwitch",
            0x07 to "SportKeyHistoryDataStart",
            0x08 to "SportKeyHistoryDataEnd",
            0x0B to "SportKeyDataTransferOnTimeRecive",
            0x0C to "SportKeyDayDataRecive",
            0x0D to "XFSmartBandCommandIdSportKeyGetDayDatas",
            0x0E to "MeasureKeyDayDataRecive",
            0x11 to "MeasreTmpDataRecive",
            0x12 to "ECGBegin",
            0x13 to "ECGEnd",
            0x14 to "SportKeySpoDataRecive"
        ),
        0x1C to mapOf(
            0x01 to "DeviceControlAppKeyFindPhone",
            0x02 to "DeviceControlAppKeyTakePhoto",
            0x03 to "DeviceControlAppKeyOpenCamera",
            0x04 to "DeviceControlAppKeyExitCamera",
            0x05 to "DeviceControlAppKeyExitHeart",
            0x06 to "DeviceControlAppKeyExitBlood",
            0x07 to "DeviceControlHangUp",
            0x08 to "DeviceControlAppKeyExitMeasure",
            0x09 to "DeviceControlAppKeyAnswerPhone",
            0x0A to "DeviceControlAppKeySwitchUp",
            0x0B to "DeviceControlAppKeySwitchPause",
            0x0C to "DeviceControlAppKeySwitchDown",
            0x0D to "DeviceControlAppKeyExitSPO",
            0x0E to "DeviceControlAppKeyStopFindPhone",
            0x0F to "DeviceControlAppKeyQueryRecentSleepResult",
            0x10 to "DeviceControlAppKeyGetTimeStramp",
            0x11 to "DeviceControlAppKeyGetAliPayTouChuan",
            0x12 to "DeviceControlAppKeyRequestDisconnectBle"
        ),
        0x1F to mapOf(
            0x01 to "DialUpdateFile",
            0x02 to "DialUpdateStart",
            0x03 to "DialUpdateFinish"
        ),
        0x20 to mapOf(
            0x01 to "DialReadStaus",
            0x02 to "DialReadInfo",
            0x03 to "DialDeviceGet"
        ),
        0x22 to mapOf(
            0x01 to "File",
            0x02 to "FileStart",
            0x03 to "FileFinish"
        ),
        0x21 to mapOf(
            0x01 to "VoiceShStart",
            0x02 to "VoiceShFinish",
            0x03 to "VoiceShData"
        ),
        0x24 to mapOf(
            0x01 to "FileVoiceChatIdSyncUserList",
            0x02 to "FileVoiceChatIdAddFriend",
            0x03 to "FileVoiceChatIdDeleteFriend",
            0x04 to "FileVoiceChatIdVoiceData",
            0x05 to "FileVoiceChatIdResetContract",
            0x06 to "FileVoiceChatIdChatHistory",
            0x07 to "FileVoiceChatIdSynUserInfo"
        ),
        0x18 to mapOf(
            0x10 to "AlarmListKeyDataRecive"
        )
    )

    fun group(g: Int): String = groups[g] ?: "grupo 0x%02X".format(g)
    fun key(g: Int, k: Int): String = keys[g]?.get(k) ?: "clave 0x%02X".format(k)
}
